language: node_js

node_js:
  - '10'

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - yarn test

jobs:
    include:
      - stage: Produce Coverage
        node_js: node
        script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
